### ISSUE TITLE
IMPROVE!!!!

### ISSUE THREAD

**Issue by sokorototo** [Imnotndesh/lyricFetchGtk#1]
Rewrite it in **RUST** and use **GTK4**.

![rust-logo-blk](https://user-images.githubusercontent.com/53893043/236922673-bb3517fc-16e8-4d50-8cca-c0ab841d8e8f.svg)

**Comment by Imnotndesh** [comment]
Still working on it

**Comment by sokorototo** [comment]
UUUURGH STILL NO RUST UUUURGHGHGHG

**Comment by Imnotndesh** [comment]
On it

**Comment by sokorototo** [comment]
imma quit the bullying

**Comment by Imnotndesh** [comment]
Already started work tho

**Comment by sokorototo** [comment]
How far are you with Rust? Might have some work for you actually
